[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cli-utilities"
version = "0.1.0"
description = "Реализации утилит nl, tail и wc на Python."
authors = [
    { name = "Ваше Имя", email = "your.email@example.com" }
]
dependencies = [

]