[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "matrixlib-slavikbendik"
version = "0.1.0"
dependencies = ["numpy>=1.24"]
requires-python = ">=3.10"
authors = [{ name = "Viacheslav Bendik" }]

[tool.hatch.build.targets.wheel]
packages = ["src/matrixlib"]